  
# Clean and don't fail
dist: xenial
language: node_js
node_js:
  - 12.16.1

# Build the Website
script:
  - npm run build
  - npm run export

deploy:
  - provider: s3
    access_key_id: $ACCESS_KEY
    secret_access_key: $SECRET_KEY
    bucket: "kostenlos-buch.de"
    region: eu-west-1
    local_dir: __sapper__/export
    skip_cleanup: true